  language: android
  sudo: required
  jdk: oraclejdk8
  env:
    global:
      - ANROID_API_LEVEL=30
      - ANDROID_BUILD_TOOLS_VERSION=30.0.2
      - ANDROID_ABI=x86
  android:
    components:
      - tools
      - platform-tools
      - build-tools-30.0.2
      - android-30
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-30
    licences:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
  before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  cache:
    directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
      - $HOME/.android/build-cache
  script :
    - ./gradlew test
    - ./gradlew connectedAndroidTest
  before_install:
    - chmod +x gradlew
  before_script:
    - echo no | android create avd --force -n test -t android-30 --abi x86 -c 512M
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell settings put global window_animation_scale 0 &
    - adb shell settings put global transition_animation_scale 0 &
    - adb shell settings put global animator_duration_scale 0 &
    - adb shell input keyevent 82 &