language: android
dist: trusty
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - extra
    - addon
    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 512M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew test
  - ./gradlew connectedAndroidTest 